---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware Tanzu's enterprise-grade software."

# VMware Tanzu Variables
  product_full: Anti-Virus for VMware Tanzu
  product_full_mirror: Anti-Virus Mirror for VMware Tanzu
  product_short: Anti-Virus
  product_short_mirror: Anti-Virus Mirror
  product_abbr: AV #Not used
  product_name: Anti-Virus #Do not use this in the future.

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs
  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI
  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS &#91;Windows&#93;

  ops_manager_full: VMware Tanzu Operations Manager
  ops_manager: Tanzu Operations Manager

  product_network: VMware Tanzu Network

# Pivotal Platform and PCF variables
  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf

  product_old: Pivotal Anti-Virus #Used in 2.0 and 2.1
  product_old_mirror: Pivotal Anti-Virus #Used in 2.0 and 2.1 (not currently in use)

# Product variables
  product_url: https://network.tanzu.vmware.com/products/p-clamav-addon/
  product_link: <div class="header-item"><a href="https://network.tanzu.vmware.com/products/p-clamav-addon/">Back to Product Page</a></div>
  support_link: <a href="http://tanzu.vmware.com/support" target="_blank">Support</a>
  support_call_to_action: <a href="http://tanzu.vmware.com/support" target="_blank">Need Support?</a>
  support_url: http://tanzu.vmware.com/support
  path_to_partials: /antivirus/partials
